"@startuml My Great Polish Application"
skinparam handwritten false

rectangle "On premis" {
    () "HTTP" as Http1
    () "HTTP" as Http2

    package "Microfrontends" {
        [Frontend 1] as Frontend1 <<React>>
        [Frontend 2] as Frontend2 <<React>>
    }

    node "Services1" {
        [Service 1] as Service1 <<SpingBoot>>
    }

    node "Services2" {
        [Service 2] as Service2 <<SpingBoot>>
    }
}

cloud "AWS" {
    database "Amazon Neptune" {
        folder "Analytics" {
            [Folder 1] as Folder1 
            [Folder 2] as Folder2 
        }
    }

}

Frontend1 <-up-> Http1
Frontend2 <-up-> Http2
Http1 <-up-> Service1
Http2 <-up-> Service2
Service1 <-left-> Folder1
Service2 <-right-> Folder2

@enduml